course = "Bachelor of commerce"
print(course)
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.find("com"))
print(course.replace("o", "A"))
print("com" in course)
print("accountancy" not in course)
